name: Setup
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 9.12.0

    - uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - name: Install node modules
      run: pnpm install --frozen-lockfile
      shell: bash
